### ISSUE TITLE
androidbinary库可以更新一下了

### ISSUE THREAD

**Issue by Zeros2619** [openatx/atx-agent#115]
github.com/shogo82148/androidbinary v1.0.1   新版本为 v1.0.5
修复了 apk.go  isMainIntentFilter方法的bug，  老版本在app有多个android.intent.action.MAIN时，返回的可能不是同时带有android.intent.category.LAUNCHER的activity。导致uiautomator2中app_start()方法拉起app失败
![image](https://github.com/openatx/atx-agent/assets/35124806/02e9b3f8-a260-49e0-9eab-f620cf8d9031)

**Comment by codeskyblue** [comment]
ref: https://github.com/openatx/uiautomator2/releases/tag/3.0.6
