### ISSUE TITLE
Too much power conumption 耗电量大

### ISSUE THREAD

**Issue by haiq2006** [openatx/atx-agent#13]
I am considering power test over ATX agent, but when I analyzed systrace, saddly the "NanoHttpd Reque" thread is always in top3 cpu usage. 
could ATX be optimized for power consumpution?

Test scenario: click popup window when installing APK

![image](https://user-images.githubusercontent.com/1872243/43458495-10fbdf1a-94fd-11e8-86c4-2cc9a0c373c4.png)

![image](https://user-images.githubusercontent.com/1872243/43458610-64af7bf8-94fd-11e8-8882-1ae6f66471d3.png)

**Comment by codeskyblue** [comment]
What is your testing code?

**Comment by codeskyblue** [comment]
There is nothing more we can do.
