### ISSUE TITLE
传输分辨率和图像质量问题

### ISSUE THREAD

**Issue by numbqq** [openatx/atx-agent#14]
`atx-agent`启动`minicap`时设置的分辨率为`800*800`，图像质量为`80`，操作正常。

但是当我把分辨率设为`1920*1080`，图像质量设置为`100`时，画面就有点卡顿了，请问你那边有这个问题吗？谢谢～

**Comment by numbqq** [comment]
我用的是千兆以太网局域网，带宽是足够的。瓶颈会在哪里呢？minicap吗？

**Comment by codeskyblue** [comment]
手机的运算速度

**Comment by 1070148808** [comment]
> `atx-agent`启动`minicap`时设置的分辨率为`800*800`，图像质量为`80`，操作正常。
> 
> 但是当我把分辨率设为`1920*1080`，图像质量设置为`100`时，画面就有点卡顿了，请问你那边有这个问题吗？谢谢～

你好，修改分辨率可以在哪里修改呢，感谢
