### ISSUE TITLE
DISCUSS: wrap every http handle func in a recoverwrap seems to enhance stableness of agent

### ISSUE THREAD

**Issue by finfou** [openatx/atx-agent#15]
Hi,
I'm performing a heavy install/uninstall app tests with atx-agent, which involves lots of repeatedly push/install/uninstall operation. Usually atx-agent die with no more than 100 apps, today after I added a recoverwrap func around every http handler, agent keeps alive after 1000 apps and it's still working. 

I can't figure out why, maybe lust lucky time. I posted it here, hope someone else could also give it a try, as agents stableness appears to be a problem when trying to run some CI tasks with atx-agents. Even after upgrade to 0.4.0 with new go daemon, it dies from time to time.

The wrap method:
func RecoverWrap(f func(w http.ResponseWriter, r *http.Request)) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		//var err error
		defer func() {
			if e := recover(); e != nil {
				log.Println("Detect panic !!!", e)
				ioutil.WriteFile("/sdcard/atx-panic.txt", []byte(fmt.Sprintf(
					"Time: %s\n%v", time.Now().Format("2006-01-02 15:04:05"),
					e)), 0644)
			}
		}()
		f(w, r)
	}
}

func RecoverWrapNew(f func(w http.ResponseWriter, r *http.Request, ws *websocket.Conn)) func(w http.ResponseWriter, r *http.Request, ws *websocket.Conn) {
	return func(w http.ResponseWriter, r *http.Request, ws *websocket.Conn){
		//var err error
		defer func() {
			if e := recover(); e != nil {
				log.Println("Detect panic !!!", e)
				ioutil.WriteFile("/sdcard/atx-panic.txt", []byte(fmt.Sprintf(
					"Time: %s\n%v", time.Now().Format("2006-01-02 15:04:05"),
					e)), 0644)
			}
		}()
		f(w, r, ws)
	}
}

And I use it like this(attempt to collect more info):
	m.HandleFunc("/version", RecoverWrap(func(w http.ResponseWriter, r *http.Request) {
		io.WriteString(w, version)
	}))

        m.HandleFunc("/upload/{target:.*}", RecoverWrap(func(w http.ResponseWriter, r *http.Request) {
...

	m.HandleFunc("/minitouch", singleFightNewerWebsocket(RecoverWrapNew(func(w http.ResponseWriter, r *http.Request, ws *websocket.Conn) {

......

BTW, during my tests there is no atx-panic.txt created, so there should be no panic captured, and the RecoveWrap seems to have no effect. (Could it because of defer()?).

I'll do more tests tomorrow.

Cheers.

**Comment by finfou** [comment]
Sorry, I switched back to 0.4.0 agent and run overnight and it didn't die, so looks like it has nothing  to do with the recoverWrap()

**Comment by codeskyblue** [comment]
it really have some bug, you are right. Donot worry it will be fuxed in 0.4.1
