### ISSUE TITLE
start atx-agent failed with msg “Unable to find instrumentation info for: ComponentInfo{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}

### ISSUE THREAD

**Issue by dragonsappire** [openatx/atx-agent#2]
when starting agent in xiaomi 3, got the error msg "Unable to find instrumentation info for: ComponentInfo{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}

here is the whole msg log:
shell@pisces:/ $ cat /storage/sdcard0/atx-agent.log
2017/10/18 10:34:17 main.go:541: Ignore SIGUP
2017/10/18 10:34:17 main.go:545: Kill server
2017/10/18 10:34:17 main.go:551: Get http://127.0.0.1:7912/stop: dial tcp 127.0.0.1:7912: getsockopt: connection refused
IP: 172.18.31.22
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner
	at com.android.commands.am.Am.runInstrument(Am.java:865)
	at com.android.commands.am.Am.onRun(Am.java:282)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:76)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:247)
	at dalvik.system.NativeStart.main(Native Method)
2017/10/18 10:34:18 main.go:188: uiautomator quit: exit status 1

I used agent with version "https://github.com/openatx/atx-agent/releases/download/0.0.5/atx-agent_0.0.5_linux_armv7.tar.gz"

my xiaomi version is MIUI 9.7.10.12 with android version 4.4.4(4.1+) 

cpuinfo:
shell@pisces:/ $ cat /proc/cpuinfo
Processor	: ARMv7 Processor rev 2 (v7l)
processor	: 0
BogoMIPS	: 1176.57

processor	: 1
BogoMIPS	: 1176.57

processor	: 2
BogoMIPS	: 1176.57

processor	: 3
BogoMIPS	: 1176.57

Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc0f
CPU revision	: 2

Hardware	: pisces
Revision	: 0000
Serial		: 062c006403430200

**Comment by dragonsappire** [comment]
after googling uiautomator usage by xiaocong, i got the solution: install two apks from https://github.com/xiaocong/uiautomator/tree/master/uiautomator/libs

please refer to issue https://github.com/xiaocong/uiautomator/issues/159

**Comment by codeskyblue** [comment]
read again readme, just updated
