### ISSUE TITLE
启动Agent时，向Server首次POST心跳请求是timestamp是空的。之后的心跳timestamp都有值。

### ISSUE THREAD

**Issue by tomqijianbo** [openatx/atx-agent#23]
0.4.5版本
启动Agent时，向Server首次POST心跳请求时timestamp是空的。之后的心跳timestamp都有值。
![image](https://user-images.githubusercontent.com/42462349/46121302-c2b56580-c245-11e8-9acf-2c6bb41fc96f.png)

**Comment by codeskyblue** [comment]
心跳逻辑 计划在 0.6.x版本修改为websocket
