### ISSUE TITLE
获取agent info有点小问题，不知道我的修改是否存在问题。

### ISSUE THREAD

**Issue by tomqijianbo** [openatx/atx-agent#24]
http://{AgentIP}:7912/info
访问这个接口时battery信息并未每次更新。查看了getDeviceInfo()方法，获取过了一次后，以后就不再更新了，除非重启agent才会重新获取。
调整了battery 代码顺序如下：
![image](https://user-images.githubusercontent.com/42462349/46130162-28681880-c26b-11e8-8b1b-ec3baaf44122.png)

同时health的值没有正确显示，一直显示为0。在Battery.go下面的update()方法里加上了health的case后就显示正常了。
不知道这么修改有没有问题，请帮我看看。
谢谢

**Comment by codeskyblue** [comment]
尝试修复了下，你测试下最新的代码有没有好使。
有个库要更新下 `go get -u -v github.com/openatx/androidutils`
