### ISSUE TITLE
uiautomator 停止状态调用 `DEL :7912/uiautomator`会500

### ISSUE THREAD

**Issue by mingyuan-xia** [openatx/atx-agent#26]
~另外建议加一个GET是获取uiautomator的当前状态~
https://github.com/openatx/atx-agent/blob/master/main.go#L760
各一个running 判断if，可惜不会写go

**Comment by codeskyblue** [comment]
uiautomator stop时调用 DEL，不再返回500，直接200，然后body为 `Already stopped`
