### ISSUE TITLE
too many open files报错 

### ISSUE THREAD

**Issue by dreamyeah** [openatx/atx-agent#27]
atx-agent.log

018/10/30 04:58:14 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:15 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:16 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:17 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:18 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:19 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:20 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:21 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:22 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:23 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:24 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s
2018/10/30 04:58:25 http: Accept error: accept tcp [::]:7912: accept4: too many open files; retrying in 1s

**Comment by codeskyblue** [comment]
这个错误是在执行了什么操作之后出现的？@dreamyeah

**Comment by codeskyblue** [comment]
另外 你看看 `/data/local/tmp/atx-agent -v`的版本号多少？

**Comment by codeskyblue** [comment]
有问题再 reopen，目前复现不了你的问题
