### ISSUE TITLE
我使用$DEVICE_URL/uiautomator启动后，为什么$DEVICE_URL/ping还是报错？

### ISSUE THREAD

**Issue by flyfire100** [openatx/atx-agent#30]
我使用$DEVICE_URL/uiautomator启动后，为什么$DEVICE_URL/ping还是报错？
![image](https://user-images.githubusercontent.com/28288582/49198477-3acb1380-f3ce-11e8-92ed-5176113889ec.png)

**Comment by codeskyblue** [comment]
说明没启动成功，可能是那个uiautomator被什么卡住了，抱歉，问题处理的很延时
