### ISSUE TITLE
华为荣耀 cor-al10 守护模式启动后，再拔掉usb，agent退出

### ISSUE THREAD

**Issue by yinjun622** [openatx/atx-agent#37]

**Comment by yinjun622** [comment]
连接华为荣耀 cor-al10
$ adb push atx-agent /data/local/tmp
$ adb shell chmod 755 /data/local/tmp/atx-agent
# launch atx-agent in daemon mode
$ adb shell /data/local/tmp/atx-agent server -d

游览器可以访问到 http://ip:7912
拔掉usb后，http://ip:7912不可访问，atx-agent消失

**Comment by ejenna** [comment]
有什么解决的方式吗，我也出现了这个问题

**Comment by yinjun622** [comment]
> 有什么解决的方式吗，我也出现了这个问题

华为需要在 开发者人员选项 中开启 仅充电模式下允许 ADB 调试

**Comment by ejenna** [comment]
> > 有什么解决的方式吗，我也出现了这个问题
> 
> 华为需要在 开发者人员选项 中开启 仅充电模式下允许 ADB 调试

开了之后并没有改善，http://ip:7912 依旧无法访问
