### ISSUE TITLE
请问获取控件的API是什么

### ISSUE THREAD

**Issue by kingyangcn** [openatx/atx-agent#47]
提个建议，个人感觉应该着重atx-agent的开发，脚本端用户可以根据自己情况使用各种语言编写测试脚本即可。作者不必对脚本端做太多封装（主要小弟不会py，虽然作者用py对脚本端做了很多封装，对我来说使用起来还是有一定学习成本，所以还是准备用自己熟悉的js或这java编写测试脚本）

**Comment by codeskyblue** [comment]
嗯，很好的建议。我考虑下
