### ISSUE TITLE
长时间运行后，agent无法访问，使用shell命令无法激活

### ISSUE THREAD

**Issue by HBoPRC** [openatx/atx-agent#51]
vivo Z3 Android 8.1.0
agent 使用的自己编译的版本

手机长时间放置后，出现 agent 无法访问的情况，重新使用 shell 命令启动输出正常，但也无法访问；log 中存在大量 runtime_pollWait，查看 agent 进程信息如下
```
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME
shell        20618     1  805524   6704 futex_wait_queue_me 0 S atx-agent
```
完整 log：[atx-agent.log](https://github.com/openatx/atx-agent/files/3523478/atx-agent.log)

**Comment by codeskyblue** [comment]
跟这个错误比较像的样子 https://github.com/golang/go/issues/10941

因为你这个是自己编译的，换个go重新编译一下

**Comment by HBoPRC** [comment]
换了 1.11 几个子版本，编译出来也会报错，还是还原成你的了，不过那个调整分辨率用不了了；

设备离线是不是也跟这个报错有关？
我看provider那边的log，每次都有几台一起重连。

**Comment by codeskyblue** [comment]
go 1.13版本

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
