### ISSUE TITLE
github.com/qiniu/log库找不到，无法编译

### ISSUE THREAD

**Issue by goodliving** [openatx/atx-agent#55]
按照安装文档步骤执行，报如下错误
$ git clone https://github.com/openatx/atx-agent
$ cd atx-agent
$ export GO111MODULE=on
$ go generate
go: finding github.com/qiniu/log v0.0.0-20140728010919-a304a74568d6
go: github.com/qiniu/log@v0.0.0-20140728010919-a304a74568d6: git fetch -f https://github.com/qiniu/log refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in D:\mygo\pkg\mod\cache\vcs\0fdd75578a3b407f676ed893d01f93d14d2c857ed66a82a1deffa8f5b4014197: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/qiniu/log/' not found
go: error loading module requirements

**Comment by codeskyblue** [comment]
坑爹的qiniu，竟然随便删库。还好我有备份。已修复
