### ISSUE TITLE
minitouch无效

### ISSUE THREAD

**Issue by xxhdxh** [openatx/atx-agent#59]
按照例子里的代码 连接有返回数据 
start @minitouch service
dial unix:@minitouch

但是发送
    {"operation": "d", "index": 0, "xP": 0.20, "yP": 0.20, "pressure": 50}
    {"operation": "c"}
屏幕没反应

**Comment by codeskyblue** [comment]
你装个atxserver2调试看看

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xxhdxh** [comment]
已经解决了 是因为之前用别的连接agent 然后没关 又连接的话是无效的 断开然后第一个连接就ok了
