### ISSUE TITLE
只要手机的ip变了，就必须要init一次，特别麻烦

### ISSUE THREAD

**Issue by Wang-Blue** [openatx/atx-agent#6]
agent有没有机制，可以让手机的ip变了就直接重新获取ip，然后发送给server。看了只要ip变了，手机后台监听就从一个ip直接变成0.0.0.0了。
不然的话手机ip变一次也要init，重启也要init，真的感觉很麻烦

**Comment by codeskyblue** [comment]
会尽快解决的，还有点技术问题需要突破

**Comment by Wang-Blue** [comment]
前排坐等大神解决

**Comment by codeskyblue** [comment]
已经解决，最新的atx-agent版本 0.3.0
将原来的使用websocket的发现发现机制，改成了http post。
ip更换后，服务端也会随之更新。
设备每10s向atx-server发送心跳包，如果设备掉线了大约20s后会检测到。
