### ISSUE TITLE
外置sdcard没有权限访问

### ISSUE THREAD

**Issue by gdbrianlu** [openatx/atx-agent#62]
2019/11/23 17:39:10 http: error reading directory: lstat storage/E3AD-1B0F/.android_secure: permission denied
127.0.0.1 - - [23/Nov/2019:17:39:10 +0800] "GET /raw/storage/E3AD-1B0F/ HTTP/1.1" 500 24

**Comment by codeskyblue** [comment]
这看起来也没什么办法。

**Comment by gdbrianlu** [comment]
可以pm grant package permission吗？

**Comment by codeskyblue** [comment]
你试试，我感觉不行

**Comment by gdbrianlu** [comment]
还有个问题想请教下，armv7/armv6/amd64/386等版本是怎么编译的，具体的编译方法

**Comment by codeskyblue** [comment]
@gdbrianlu https://blog.csdn.net/panshiqu/article/details/53788067
