### ISSUE TITLE
编译时提示410 Gone，go.mod需要更新吗

### ISSUE THREAD

**Issue by gdbrianlu** [openatx/atx-agent#64]
verifying github.com/franela/goblin@v0.0.0-20181003173013-ead4ad1d2727/go.mod: github.com/franela/goblin@v0.0.0-20181003173013-ead4ad1d2727/go.mod: reading https://goproxy.io/sumdb/sum.golang.org/lookup/github.com/franela/goblin@v0.0.0-20181003173013-ead4ad1d2727: 410 Gone
verifying gopkg.in/check.v1@v1.0.0-20190902080502-41f04d3bba15/go.mod: gopkg.in/check.v1@v1.0.0-20190902080502-41f04d3bba15/go.mod: reading https://goproxy.io/sumdb/sum.golang.org/lookup/gopkg.in/check.v1@v1.0.0-20190902080502-41f04d3bba15: 410 Gone
verifying github.com/rs/cors@v1.6.0/go.mod: github.com/rs/cors@v1.6.0/go.mod: reading https://goproxy.io/sumdb/sum.golang.org/lookup/github.com/rs/cors@v1.6.0: 410 Gone

**Comment by codeskyblue** [comment]
刚试了试没什么问题，感觉是你配置了代理的问题

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gdbrianlu** [comment]
编译启动了，报其他问题：
./httpserver.go:1177:73: undefined: Assets
./main.go:265:15:undefine:Assets
