### ISSUE TITLE
重启手机后，连接不上atx-server

### ISSUE THREAD

**Issue by Wang-Blue** [openatx/atx-agent#7]
首先很感谢大佬把手机换ip的问题用heartbeat修复了。但是发现手机重启后，仍然需要init一次。所以想uiautomator.apk上是否可以新增一个重新连接atx-server的按钮呢。
我试了启动atx-agent命令，可以启动atx-agent，但是不能重新再连接上atx-server了：adb shell /data/local/tmp/atx-agent -d，是否我还需要执行其他命令才能重新连接上。
![1](https://user-images.githubusercontent.com/12178859/39417819-61d490ba-4c89-11e8-8799-5f1c95c3985b.png)
![2](https://user-images.githubusercontent.com/12178859/39417820-62145132-4c89-11e8-966b-161fc3b9bc59.png)

**Comment by codeskyblue** [comment]
少了一个参数 -t 服务器地址   
另外apk没有这么高的权限，只能用命令行

**Comment by Wang-Blue** [comment]
@codeskyblue apk没有这么高权限的话，那是否atx-agent可以做成重启手机后自动运行呢

**Comment by codeskyblue** [comment]
Android系统并不是标准的Linux系统，我还不知道怎么改自启动项

**Comment by jyzhkj** [comment]
用一个能自动启动的apk调用shell指令来启动atx-agent就行.
