### ISSUE TITLE
adb shell /data/local/tmp/atx-agent -d 2018/05/21 03:09:58 main.go:1216: server started failed, <nil> 无法启动

### ISSUE THREAD

**Issue by 342164796** [openatx/atx-agent#8]
adb shell /data/local/tmp/atx-agent -d
2018/05/21 03:09:58 main.go:1216: server started failed, <nil>无法启动
adb shell /data/local/tmp/atx-agent
可以正常启动 
参数 -d 是什么作用呢？

**Comment by codeskyblue** [comment]
-d代码，后台启动的意思。把错误信息也贴出来。我可猜不出来

**Comment by codeskyblue** [comment]
长时间无答复，关闭
