### ISSUE TITLE
打包amd64架构的包后，无法执行该文件

### ISSUE THREAD

**Issue by HOTTIN** [openatx/atx-agent#99]
使用命令打包
`GOOS=linux GOARCH=amd64 go build -tags vfs -buildvcs=false`
得到的文件，通过file命令查看如下
`➜  ~ file atx-agent 
atx-agent: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=K63F_zlQ0ULE06Yf090T/-qorvRodqhXaRxHv2t_f/3xaJdDogbkVqaoibSllw/6DUXqOViYjhObFBs12Ki, stripped`
但是我在执行atx-agent的机器上没有根目录的权限，无法将这个so放到指定位置，请问这个怎么能解决？

**Comment by HOTTIN** [comment]
已解决
`export CGO_ENABLED=0`

**Comment by codeskyblue** [comment]
竟然还有amd64架构的手机
